Feat : DaisyUI components implementation (HBP-2)
tomconversion/ui pull request #2
Opened 2023-02-21 05:51 UTC by g1mishra

2023-02-21 05:59 UTC, tomconversion requested changes

2023-02-21 05:59 UTC, tomconversion commented on components/ui/cards/CardImage.tsx
> +      <img {...rest} />
Please use react/image

2023-02-21 05:59 UTC, tomconversion commented on components/ui/demo/breadcrumbdemo.tsx
> +        <Breadcrumbs.Item href="#home">Home</Breadcrumbs.Item>
Please update the demo so that a JSON data structure is used to populate the breadcrumbs. Show the JSON data on the demo page so that developers can easily view it.  ChatGPT can be used to easily create the JSON for you if you give it the React code first and ask it to give you to modify the component to accept a JSON object for data instead.

2023-02-21 05:59 UTC, tomconversion commented on components/ui/demo/footer.demo.tsx
> +      <Footer className="bg-neutral p-10 text-neutral-content">
Please update the demo so that a JSON data structure is used to populate the footer. Show the JSON data on the demo page so that developers can easily view it.  ChatGPT can be used to easily create the JSON for you if you give it the React code first and ask it to give you to modify the component to accept a JSON object for data instead.

2023-02-21 11:33 UTC, g1mishra commented on components/ui/demo/breadcrumbdemo.tsx
> +        <Breadcrumbs.Item href="#home">Home</Breadcrumbs.Item>
Done

2023-02-21 11:34 UTC, g1mishra commented on components/ui/cards/CardImage.tsx
> +      <img {...rest} />
Done

2023-02-21 18:06 UTC, g1mishra commented on components/ui/demo/footer.demo.tsx
> +      <Footer className="bg-neutral p-10 text-neutral-content">
Done

2023-02-22 06:17 UTC, tomconversion approved these changes

2023-02-22 06:18 UTC, merged